### ISSUE TITLE
Step 5. is not clear, there should be an example for them also

### ISSUE THREAD

**Issue by metinilhan** [MicrosoftDocs/powerbi-docs.tr-tr#2]
Which user name and password, example would be greate. I tried alot but no result

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: cdd3eb8d-0f4f-e8cd-7ed3-5ceccc433ddd
* Version Independent ID: 2164905a-fae3-c9e8-a62f-08d9b7ac95de
* Content: [Power BI ile Microsoft Dynamics NAV'a bağlanma - Power BI](https://docs.microsoft.com/tr-tr/power-bi/service-connect-to-microsoft-dynamics-nav#feedback)
* Content Source: [powerbi-docs/service-connect-to-microsoft-dynamics-nav.md](https://github.com/MicrosoftDocs/powerbi-docs.tr-tr/blob/live/powerbi-docs/service-connect-to-microsoft-dynamics-nav.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by CeciAc** [comment]
Hello, @metinilhan 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
