### ISSUE TITLE
Custom List as Filter

### ISSUE THREAD

**Issue by ofyayla** [MicrosoftDocs/powerbi-docs.tr-tr#4]
We use SSAS models in my company and I am a end-user of the model. I create own dashboards with the cube datas.
Sometimes for the spesifics customer group I need to filter them on the model. 
For example I have 1million customer but I want to create a special analysis for 50K number list specifically. 
I tried to custom visual like filter by list by Devscope but when add numbers it stucks.
Is there a solution for that?

**Comment by srvbpigh** [comment]
Hello, @ofyayla
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @ofyayla, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/2097. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by paulinbar** [comment]
Hi @ofyayla , @srvbpigh , and @CeciAc . Do any of you have a reference to the doc page in question? We are the doc team and in order to be able to check the issue we need to be able to know what doc(s) are being referred to. If it is a product question or a support request, I suggest you try either the [Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com). Thanks!
